theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端开发工程师

# 对你自己的简洁描述
description: 努力适应新生活的小白

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: 洪芋

# 你的联系方式
phone: 15237363931

# 你的邮箱
email: ishongy@163.com

# 你目前的住址
address: 河南省新乡市

# 你毕业院校
school: 郑州航空工业管理学院

# 你的专业
profession: 计算机科学与技术

# 你的学位
degree: 本科

# 你获得过的证书或奖励
credential: 英语六级/优秀共青团员/校奖学金
